CREATE DATABASE QUOC
GO
USE QUOC
GO

CREATE TABLE DANHMUC(
    MADM VARCHAR(10) PRIMARY KEY,
    TENDM NVARCHAR(50)
)

GO
CREATE TABLE SANPHAM(
    MASP VARCHAR(10) PRIMARY KEY,
    TENSP NVARCHAR(50),
    SOLUONG INT,
    DONGIA FLOAT,
    KHUYENMAI FLOAT,
    MOTA_NGAN NVARCHAR(100),
    MOTA_CHITIET NVARCHAR(500),
    PHOTO NVARCHAR(500),
    MADM VARCHAR(10) FOREIGN KEY REFERENCES DANHMUC(MADM)
)

GO
CREATE TABLE QUYEN(
    MAQUYEN INT PRIMARY KEY,
    TENQUYEN NVARCHAR(50)
)
GO
CREATE TABLE TAIKHOAN(
    MATK INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    MAQUYEN INT FOREIGN KEY REFERENCES QUYEN(MAQUYEN)

)
GO
CREATE TABLE KHACHHANG(
    MAKH VARCHAR(10) PRIMARY KEY,
    MATK INT UNIQUE,
    HO NVARCHAR(50),
    TEN NVARCHAR(50),
    GIOITINH INT,
    SDT VARCHAR(11),
    EMAIL VARCHAR(50),
    DIACHI NVARCHAR(100),
    FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK)
)
GO
CREATE TABLE NHANVIEN(
    MANV VARCHAR(10) PRIMARY KEY,
    MATK INT UNIQUE,
    HO NVARCHAR(50),
    TEN NVARCHAR(50),
    GIOITINH INT,
    SDT VARCHAR(11),
    EMAIL VARCHAR(50),
    DIACHI NVARCHAR(100),
    LUONG FLOAT,
    FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK)
)
GO
CREATE TABLE BINHLUAN(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOIDUNG NVARCHAR(500),
    TIME DATETIME,
    MASP VARCHAR(10) FOREIGN KEY REFERENCES SANPHAM(MASP),
    MAKH VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKH)
)
GO
CREATE TABLE DANHGIA(
    MASP VARCHAR(10) FOREIGN KEY REFERENCES SANPHAM(MASP),
    MAKH VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    DANHGIA INT,
    PRIMARY KEY(MASP,MAKH)
)
GO
CREATE TABLE GIOHANG(
    MASP VARCHAR(10) FOREIGN KEY REFERENCES SANPHAM(MASP),
    MAKH VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    SOLUONG INT,
    PRIMARY KEY(MASP,MAKH)
)
GO
CREATE TABLE DONHANG(
    MADH VARCHAR(10) PRIMARY KEY,
    HINHTHUCTHANHTOAN INT,
    NGAYDAT DATETIME,
    TONGTIEN FLOAT,
    TRANGTHAI INT,
    MAKH VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKH),
    MANV VARCHAR(10) FOREIGN KEY REFERENCES NHANVIEN(MANV)
)
GO
CREATE TABLE CTDH(
    MADH VARCHAR(10) FOREIGN KEY REFERENCES DONHANG(MADH),
    MASP VARCHAR(10) FOREIGN KEY REFERENCES SANPHAM(MASP),
    SOLUONG INT,
    PRIMARY KEY(MADH,MASP)
)

GO

INSERT INTO QUYEN VALUES (1,'Admin')
INSERT INTO QUYEN VALUES (2,'Khachhang')
INSERT INTO QUYEN VALUES (3,'NHANVIEN')
INSERT INTO TAIKHOAN VALUES ('QUOC','123',1)


select * from taikhoan